version: '3.6'
services:
  bot:
    build: .
    depends_on:
      - db
    secrets:
      - token
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - 'db-data:/data/db'

volumes:
  db-data:

secrets:
  token:
    file: ./token.txt